# style_registry.py
#
# !!! THIS FILE IS AUTO-GENERATED BY build_registries.py !!!
# !!! DO NOT EDIT MANUALLY. YOUR CHANGES WILL BE OVERWRITTEN. !!!
#
# This file contains the explicit list of all tool-specific stylesheets
# to be included in the application.

# --- Style Module Imports ---

# --- Style Module Imports ---
from tools.max_length import max_length_styles as max_length_styles_module
from tools.merge import merge_styles as merge_styles_module
from tools.min_length import min_length_styles as min_length_styles_module
from tools.multilingual_merge import multilingual_merge_styles as multilingual_merge_styles_module
from tools.placeholder_tool import placeholder_tool_styles as placeholder_tool_styles_module
from tools.split import split_styles as split_styles_module
from tools.srt_editor import srt_editor_styles as srt_editor_styles_module
from tools.subtitle_converter import subtitle_converter_styles as subtitle_converter_styles_module
from tools.subtitle_shifter import subtitle_shifter_styles as subtitle_shifter_styles_module

# --- Style Template Registration Dictionary ---
REGISTERED_STYLE_TEMPLATES = {
    "max_length": max_length_styles_module.STYLE_TEMPLATE,
    "merge": merge_styles_module.STYLE_TEMPLATE,
    "min_length": min_length_styles_module.STYLE_TEMPLATE,
    "multilingual_merge": multilingual_merge_styles_module.STYLE_TEMPLATE,
    "placeholder_tool": placeholder_tool_styles_module.STYLE_TEMPLATE,
    "split": split_styles_module.STYLE_TEMPLATE,
    "srt_editor": srt_editor_styles_module.STYLE_TEMPLATE,
    "subtitle_converter": subtitle_converter_styles_module.STYLE_TEMPLATE,
    "subtitle_shifter": subtitle_shifter_styles_module.STYLE_TEMPLATE,
}
