# tool_registry.py
#
# !!! THIS FILE IS AUTO-GENERATED BY build_registries.py !!!
# !!! DO NOT EDIT MANUALLY. YOUR CHANGES WILL BE OVERWRITTEN. !!!
#
# This file contains the explicit list of all tools to be included in the
# application. It is used by the tool_loader to populate the list of
# available tools in a way that is compatible with compilers like Nuitka.

# --- Tool Module Imports ---
# Nuitka will trace these imports and include them in the final build.

# --- Tool Module Imports ---
from tools.max_length import max_length as max_length_module
from tools.merge import merge as merge_module
from tools.min_length import min_length as min_length_module
from tools.multilingual_merge import multilingual_merge as multilingual_merge_module
from tools.placeholder_tool import placeholder_tool as placeholder_tool_module
from tools.split import split as split_module
from tools.srt_editor import srt_editor as srt_editor_module
from tools.subtitle_converter import subtitle_converter as subtitle_converter_module
from tools.subtitle_shifter import subtitle_shifter as subtitle_shifter_module

# --- Tool Registration List ---
# The tool_loader will iterate through this list to build the AVAILABLE_TOOLS dict.
REGISTERED_TOOL_MODULES = [
    max_length_module,
    merge_module,
    min_length_module,
    multilingual_merge_module,
    placeholder_tool_module,
    split_module,
    srt_editor_module,
    subtitle_converter_module,
    subtitle_shifter_module,
]
