name: Individual OS Dev Build

on:
  push:
    branches:
      - 'dev-windows'
      - 'dev-ubuntu'
      - 'dev-macos'

jobs:
  call-reusable-build:
    # This job now has two steps
    runs-on: ubuntu-latest # A runner is needed for the first step
    steps:
      # Step 1: Extract the OS name from the branch and set it as an output
      - name: Set OS from branch name
        id: get_os # Give the step an ID to reference its outputs
        run: echo "os_name=${GITHUB_REF_NAME#dev-}" >> $GITHUB_OUTPUT

      # Step 2: Call the reusable workflow using the output from the previous step
      - name: Call Reusable Build Workflow
        uses: ./.github/workflows/reusable-build.yml
        with:
          os: ${{ steps.get_os.outputs.os_name }} # Use the output here
          version_tag: ${{ github.ref_name }}
          environment_name: 'Development'
          secrets: inherit