name: Individual OS Dev Build

on:
  push:
    branches:
      - 'dev-windows'
      - 'dev-ubuntu'
      - 'dev-macos'

jobs:
  # JOB 1: Determine the parameters for the build
  setup:
    runs-on: ubuntu-latest
    outputs:
      os_name: ${{ steps.get_os.outputs.os_name }}
      version_tag: ${{ github.ref_name }}
    steps:
      - name: Set OS from branch name
        id: get_os
        run: echo "os_name=${GITHUB_REF_NAME#dev-}" >> $GITHUB_OUTPUT

  # JOB 2: Call the workflow using the parameters from the setup job
  call-build:
    needs: setup
    # CORRECTED LINE: Use the full, dynamic path to the workflow in your repository
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ needs.setup.outputs.os_name }}
      version_tag: ${{ needs.setup.outputs.version_tag }}
      environment_name: 'Development'
    secrets: inherit