name: Create GitHub Release

on:
  workflow_run:
    workflows: ["Stable Release", "Early Release Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required to create a release
    steps:
      - name: Set Release Properties
        id: set_release_props
        run: |
          if [ "${{ github.event.workflow_run.name }}" == "Stable Release" ]; then
            echo "prerelease=false" >> $GITHUB_OUTPUT
            echo "release_name=Release ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          else
            echo "prerelease=true" >> $GITHUB_OUTPUT
            echo "release_name=Pre-release ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          fi

      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*/*"
          tag: ${{ github.event.workflow_run.head_branch }}
          name: ${{ steps.set_release_props.outputs.release_name }}
          prerelease: ${{ steps.set_release_props.outputs.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true  # Add this line to create a draft release