name: Stable Release

on:
  push:
    tags:
      - 'v*.*.*' # e.g., v1.2.3

jobs:
  call-reusable-build:
    uses: ./.github/workflows/build.yml
    with:
      os: 'all'
      version_tag: ${{ github.ref_name }}
      # Pass the specific environment name
      environment_name: 'Release-stable'
    secrets: inherit